### PR TITLE
Renaming for zkVerify node env var

### PR DESCRIPTION
**Pull request by JackPiri**
"NH_" -> "ZKV_"

## Description
Renaming prefix from `NH` (New Horizen) to `ZKV` (zkVerify)

## Jira Ticket
[ZKV-557](https://horizenlabs.atlassian.net/browse/ZKV-557)

## Changes
Renaming

## Breaking Changes
To be checked the script `update.sh`

## Checks
- [ ] Project Builds
- [ ] Project passes tests and checks
- [ ] Updated documentation accordingly
- [ ] Breaking changes have been correctly tagged and notified

## Additional information
Motivated by this [PR] (https://github.com/HorizenLabs/zkVerify/pull/96)

### CODE REVIEW

**Review by ysibirski — CHANGES_REQUESTED** [review]
under utils.sh docker run command occurring twice is using `nh-node` binary

```
docker run --rm --entrypoint nh-node horizenlabs/zkverify:"${NODE_VERSION}" key generate-node-key 2>/dev/nul
```

**Comment by JackPiri** [comment]
> under utils.sh docker run command occurring twice is using `nh-node` binary
> 
> ```
> docker run --rm --entrypoint nh-node horizenlabs/zkverify:"${NODE_VERSION}" key generate-node-key 2>/dev/nul
> ```

Thank you for spotting those lines, modified accordingly (and force-pushed).

**Review by otoumas — APPROVED** [review]
LGTM

**Review by ysibirski — APPROVED** [review]
LGTM

**Pull request merged**
